version: '3.9'
services:
  my-sql:
    image: mysql:8.0
    ports:
    - 3306:3306
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learn-nest
      MYSQL_USER: thodh
      MYSQL_PASSWORD: root
    volumes:
      - type: bind
        source: ./data/mysql
        target: /var/lib/mysql
